   
CREATE TABLE USUARIO
(
I_USR_ID INTEGER NOT NULL CONSTRAINT PK_I_USR_ID PRIMARY KEY,
V_USR_USUARIO VARCHAR(50) NOT NULL,
V_USR_CLAVE VARCHAR(50) NOT NULL,
I_USR_PER_ID INTEGER NOT NULL,
I_USR_ID_CREA INTEGER NOT NULL,
D_USR_FEC_CREA DATE NOT NULL,
I_USR_ID_ACTU INTEGER NULL,
D_USR_FEC_ACTU DATE NULL
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_I_USR_ID_CREA FOREIGN KEY (I_USR_ID_CREA) REFERENCES USUARIO(I_USR_ID);
ALTER TABLE USUARIO
ADD CONSTRAINT FK_I_USR_ID_ACTU FOREIGN KEY (I_USR_ID_ACTU) REFERENCES USUARIO(I_USR_ID);

CREATE TABLE MENU
(
I_MEN_ID INTEGER NOT NULL CONSTRAINT PK_I_MEN_ID PRIMARY KEY,
V_MEN_DESCRIPCION VARCHAR(50) NULL,
C_MEN_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_MEN_ORDEN INTEGER DEFAULT 1 NOT NULL,
V_RUTA VARCHAR(200) NULL,
I_MEN_ID_PADRE INTEGER NULL,
I_MEN_ID_USR_CREA INTEGER NOT NULL,
D_MEN_FEC_CREA DATE NOT NULL,
I_MEN_ID_USR_ACTU INTEGER NULL,
D_MEN_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_MEN_ID_USR_CREA FOREIGN KEY (I_MEN_ID_USR_CREA) REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_MEN_ID_USR_ACTU	FOREIGN KEY (I_MEN_ID_USR_ACTU)	REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_MEN_ID_PADRE FOREIGN KEY (I_MEN_ID_PADRE) REFERENCES MENU (I_MEN_ID)
);

CREATE TABLE PERFIL
(
I_PER_ID INTEGER NOT NULL CONSTRAINT PK_I_PER_ID PRIMARY KEY,
V_PER_DESCRIPCION VARCHAR(50) NULL,
C_PER_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_PER_ID_USR_CREA INTEGER NOT NULL,
D_PER_FEC_CREA DATE NOT NULL,
I_PER_ID_USR_ACTU INTEGER NULL,
D_PER_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_PER_ID_USR_CREA FOREIGN KEY (I_PER_ID_USR_CREA) REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_PER_ID_USR_ACTU	FOREIGN KEY (I_PER_ID_USR_ACTU)	REFERENCES USUARIO (I_USR_ID)
);

CREATE TABLE MENU_PERFIL
(
I_MEN_ID INTEGER NOT NULL,
I_PER_ID INTEGER NOT NULL,
I_MENPER_ID_USR_CREA INTEGER NOT NULL,
D_MENPER_FEC_CREA DATE NOT NULL,
I_MENPER_ID_USR_ACTU INTEGER NULL,
D_MENPER_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_MENPER_ID_USR_CREA FOREIGN KEY (I_MENPER_ID_USR_CREA) REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_MENPER_ID_USR_ACTU FOREIGN KEY (I_MENPER_ID_USR_ACTU)  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT PK_I_MENPER_ID PRIMARY KEY (I_MEN_ID,I_PER_ID),
CONSTRAINT FK_I_MENPER_ID_MEN FOREIGN KEY (I_MEN_ID) REFERENCES MENU (I_MEN_ID),
CONSTRAINT FK_I_MENPER_ID_PER FOREIGN KEY (I_PER_ID)  REFERENCES PERFIL (I_PER_ID)
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_I_USR_PER_ID FOREIGN KEY (I_USR_PER_ID) REFERENCES PERFIL(I_PER_ID);

CREATE TABLE TIPO_DOCUMENTO
(
I_DOC_ID INTEGER NOT NULL CONSTRAINT PK_I_ID_TIPODOC PRIMARY KEY,
V_DOC_CODIGO VARCHAR(15) NULL,
V_DOC_DESCRIPCION VARCHAR(100) NULL,
I_DOC_ORDEN INTEGER DEFAULT 1 NOT NULL,
C_DOC_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_DOC_ID_USR_CREA INTEGER NOT NULL,
D_DOC_FEC_CREA DATE NOT NULL,
I_DOC_ID_USR_ACTU INTEGER NULL,
D_DOC_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_DOC_ID_USR_CREA
	FOREIGN KEY (I_DOC_ID_USR_CREA)
	REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_DOC_ID_USR_ACTU
	FOREIGN KEY (I_DOC_ID_USR_ACTU)
	REFERENCES USUARIO (I_USR_ID)
);

CREATE TABLE SEXO
(
I_SEX_ID INTEGER NOT NULL CONSTRAINT PK_I_SEX_IDC PRIMARY KEY, 
V_SEX_DESCRIPCION VARCHAR(50) NOT NULL,
C_SEX_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_SEX_ID_USR_CREA INTEGER NOT NULL,
D_SEX_FEC_CREA DATE NOT NULL,
I_SEX_ID_USR_ACTU INTEGER NULL,
D_SEX_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_SEX_ID_USR_CREA
	FOREIGN KEY (I_SEX_ID_USR_CREA)
	REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_SEX_ID_USR_ACTU
	FOREIGN KEY (I_SEX_ID_USR_ACTU)
	REFERENCES USUARIO (I_USR_ID)
);

CREATE TABLE GRADO
(
I_GRD_ID INTEGER NOT NULL CONSTRAINT PK_I_GRD_ID PRIMARY KEY,
V_GRD_DESCRIPCION VARCHAR(25) NULL,
I_GRD_TOTAL INTEGER NULL,
C_GRD_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_GRD_ID_USR_CREA INTEGER NOT NULL,
D_GRD_FEC_CREA DATE NOT NULL,
I_GRD_ID_USR_ACTU INTEGER NULL,
D_GRD_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_GRD_ID_USR_CREA
	FOREIGN KEY (I_GRD_ID_USR_CREA)
	REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_GRD_ID_USR_ACTU
	FOREIGN KEY (I_GRD_ID_USR_ACTU)
	REFERENCES USUARIO (I_USR_ID)
);

CREATE TABLE AULA
(
I_AUL_ID INTEGER NOT NULL CONSTRAINT PK_I_AUL_ID PRIMARY KEY,
I_AUL_TOTAL INTEGER NULL,
I_AUL_AFORO INTEGER NULL,
C_AUL_ESTADO CHAR(1) DEFAULT '1' NOT NULL,
I_AUL_ID_USR_CREA INTEGER NOT NULL,
D_AUL_FEC_CREA DATE NOT NULL,
I_AUL_ID_USR_ACTU INTEGER NULL,
D_AUL_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_AUL_ID_USR_CREA
	FOREIGN KEY (I_AUL_ID_USR_CREA)
	REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_AUL_ID_USR_ACTU
	FOREIGN KEY (I_AUL_ID_USR_ACTU)
	REFERENCES USUARIO (I_USR_ID)
);

CREATE TABLE PROFESOR
(
I_PRF_ID INTEGER NOT NULL CONSTRAINT PK_I_PRF_ID PRIMARY KEY,
I_PRF_DOC_ID INTEGER NOT NULL,
V_PRF_NOMBRES VARCHAR(150) NULL,
V_PRF_APE_PAT VARCHAR(150) NULL,
V_PRF_APE_MAT VARCHAR(150) NULL,
I_PRF_ID_SEXO INTEGER NOT NULL,
V_PRF_DIRECCION VARCHAR(250) NULL,
V_PRF_TELEFONO VARCHAR(15) NULL,
I_PRF_EDAD INTEGER NULL,
D_PRF_FEC_NACI DATE NOT NULL,
I_PRF_ID_USR INTEGER NULL,
I_PRF_ID_USR_CREA INTEGER NOT NULL,
D_PRF_FEC_CREA DATE NOT NULL,
I_PRF_ID_USR_ACTU INTEGER NULL,
D_PRF_FEC_ACTU DATE NULL,  
CONSTRAINT FK_I_PRF_ID_USR
  FOREIGN KEY (I_PRF_ID_USR)
  REFERENCES USUARIO (I_USR_ID), 
CONSTRAINT FK_I_PRF_ID_USR_CREA
  FOREIGN KEY (I_PRF_ID_USR_CREA)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_PRF_ID_USR_ACTU
  FOREIGN KEY (I_PRF_ID_USR_ACTU)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_PRF_DOC_IDU
  FOREIGN KEY (I_PRF_DOC_ID)
  REFERENCES TIPO_DOCUMENTO (I_DOC_ID),
CONSTRAINT FK_I_PRF_ID_SEXO
  FOREIGN KEY (I_PRF_ID_SEXO)
  REFERENCES SEXO (I_SEX_ID)
);

CREATE TABLE PADRE
(
I_PDR_ID INTEGER NOT NULL CONSTRAINT PK_I_PDR_ID PRIMARY KEY,
I_PDR_DOC_ID INTEGER NOT NULL,
V_PDR_NOMBRES VARCHAR(150) NULL,
V_PDR_APE_PAT VARCHAR(150) NULL,
V_PRF_APE_MAT VARCHAR(150) NULL,
I_PDR_ID_SEXO INTEGER NOT NULL,
V_PDR_DIRECCION VARCHAR(250) NULL,
V_PDR_TELEFONO VARCHAR(15) NULL,
I_PDR_EDAD INTEGER NULL,
D_PDR_FEC_NACI DATE NOT NULL,
I_PDR_ID_USR INTEGER NULL,
I_PDR_ID_USR_CREA INTEGER NOT NULL,
D_PDR_FEC_CREA DATE NOT NULL,
I_PDR_ID_USR_ACTU INTEGER NULL,
D_PDR_FEC_ACTU DATE NULL,  
CONSTRAINT FK_I_PDR_ID_USR
  FOREIGN KEY (I_PDR_ID_USR)
  REFERENCES USUARIO (I_USR_ID), 
CONSTRAINT FK_I_PDR_ID_USR_CREA
  FOREIGN KEY (I_PDR_ID_USR_CREA)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_PDR_ID_USR_ACTU
  FOREIGN KEY (I_PDR_ID_USR_ACTU)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_PDR_DOC_IDU
  FOREIGN KEY (I_PDR_DOC_ID)
  REFERENCES TIPO_DOCUMENTO (I_DOC_ID),
CONSTRAINT FK_I_PDR_ID_SEXO
  FOREIGN KEY (I_PDR_ID_SEXO)
  REFERENCES SEXO (I_SEX_ID)
);

CREATE TABLE ALUMNO
(
I_ALM_ID INTEGER NOT NULL CONSTRAINT PK_I_ALM_ID PRIMARY KEY,
I_ALM_DOC_ID INTEGER NOT NULL,
V_ALM_NOMBRES VARCHAR(150) NULL,
V_ALM_APE_PAT VARCHAR(150) NULL,
V_ALM_APE_MAT VARCHAR(150) NULL,
I_ALM_ID_SEXO INTEGER NOT NULL,
V_ALM_DIRECCION VARCHAR(250) NULL,
V_ALM_TELEFONO VARCHAR(15) NULL,
I_ALM_EDAD INTEGER NULL,
D_ALM_FEC_NACI DATE NOT NULL,
I_ALM_ID_USR INTEGER NULL,
I_ALM_ID_GRD INTEGER NULL,
I_ALM_ID_PDR INTEGER NULL,
I_ALM_ID_USR_CREA INTEGER NOT NULL,
D_ALM_FEC_CREA DATE NOT NULL,
I_ALM_ID_USR_ACTU INTEGER NULL,
D_ALM_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_ALM_ID_GRD
  FOREIGN KEY (I_ALM_ID_GRD)
  REFERENCES GRADO (I_GRD_ID),
CONSTRAINT FK_I_ALM_ID_PDR
  FOREIGN KEY (I_ALM_ID_PDR)
  REFERENCES PADRE (I_PDR_ID),
CONSTRAINT FK_I_ALM_ID_USR
  FOREIGN KEY (I_ALM_ID_USR)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_ALM_ID_USR_CREA
  FOREIGN KEY (I_ALM_ID_USR_CREA)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_ALM_ID_USR_ACTU
  FOREIGN KEY (I_ALM_ID_USR_ACTU)
  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_ALM_DOC_IDU
  FOREIGN KEY (I_ALM_DOC_ID)
  REFERENCES TIPO_DOCUMENTO (I_DOC_ID),
CONSTRAINT FK_I_ALM_ID_SEXO
  FOREIGN KEY (I_ALM_ID_SEXO)
  REFERENCES SEXO (I_SEX_ID)
);

CREATE TABLE MATRICULA
(
I_MAT_ID INTEGER NOT NULL CONSTRAINT PK_I_MAT_ID PRIMARY KEY,
I_MAT_ID_ALM INTEGER NOT NULL,
I_MAT_ID_AULA INTEGER NOT NULL,
I_MAT_ID_GRD INTEGER NOT NULL,
I_MAT_FEC_INI INTEGER NOT NULL,
I_MAT_FEC_FIN INTEGER NOT NULL,
I_MAT_PAGO DECIMAL NOT NULL,
I_MAT_ESTADO VARCHAR(25) NOT NULL,
I_MAT_ID_USR_CREA INTEGER NOT NULL,
D_MAT_FEC_CREA DATE NOT NULL,
I_MAT_ID_USR_ACTU INTEGER NULL,
D_MAT_FEC_ACTU DATE NULL,   
CONSTRAINT FK_I_MAT_ID_USR_CREA FOREIGN KEY (I_MAT_ID_USR_CREA) REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_MAT_ID_USR_ACTU FOREIGN KEY (I_MAT_ID_USR_ACTU)  REFERENCES USUARIO (I_USR_ID),
CONSTRAINT FK_I_MAT_ID_ALM FOREIGN KEY (I_MAT_ID_ALM) REFERENCES ALUMNO (I_ALM_ID),
CONSTRAINT FK_I_MAT_ID_AULA FOREIGN KEY (I_MAT_ID_AULA)  REFERENCES AULA (I_AUL_ID),
CONSTRAINT FK_I_MAT_ID_GRD FOREIGN KEY (I_MAT_ID_GRD)  REFERENCES GRADO (I_GRD_ID)
);


